name: Release

on:
  pull_request:
    types: [closed]
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile
          
      - name: Configure Git
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
      - name: Bump version
        run: |
          echo "NEW_VERSION=$(npm version patch -m 'chore(release): bump version to %s')" >> $GITHUB_ENV
          
      - name: Generate Changelog
        run: |
          pnpm add -D conventional-changelog-cli
          npx conventional-changelog -p angular -i CHANGELOG.md -s
          
      - name: Commit changes
        run: |
          git add CHANGELOG.md package.json
          git commit -m "chore(release): update changelog for ${{ env.NEW_VERSION }}"
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
